### PR TITLE
optimize: use python:3.6-alpine

### PR DESCRIPTION
**Pull request by k8scat**

### CODE REVIEW

**Comment by k8scat** [comment]
image
`germey/proxypool` was built based on python:3.6-alpine and `germey/proxypool-origin` was built based on python:3.6, `germey/proxypool` based on python:3.6-alpine will take less space that's about 700 MB.

And this PR has been tested, it worked correctly!

**Comment by plokid** [comment]
@k8scat you even can delete gcc and musl-dev after pip install, that will make the image much smaller.

**Comment by k8scat** [comment]
> @k8scat you even can delete gcc and musl-dev after pip install, that will make the image much smaller.

yes, it's right, and I have removed some build pkgs: `apk del gcc musl-dev libxml2-dev`

**Comment by Germey** [comment]
Thanks for your contribution!

**Pull request merged**
